# Конфигурация для Railway Nixpacks

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install --legacy-peer-deps"]
cacheDirectories = []

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "npm start"